# Generated by Django 5.2.7 on 2025-10-04 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('stop_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_course', models.CharField(max_length=100)),
                ('subject_code_course', models.CharField(max_length=20)),
                ('subject_name_course', models.CharField(max_length=100)),
                ('student_group_name_course', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_course', models.CharField(blank=True, default='', max_length=50)),
                ('section_course', models.CharField(max_length=10)),
                ('theory_slot_amount_course', models.IntegerField(default=0)),
                ('lab_slot_amount_course', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('student_group', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('hours', models.IntegerField(default=0)),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_pre', models.CharField(max_length=100)),
                ('subject_code_pre', models.CharField(max_length=20)),
                ('subject_name_pre', models.CharField(max_length=100)),
                ('student_group_name_pre', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_pre', models.CharField(blank=True, default='', max_length=50)),
                ('type_pre', models.CharField(max_length=20)),
                ('hours_pre', models.IntegerField(default=0)),
                ('section_pre', models.CharField(max_length=10)),
                ('day_pre', models.CharField(blank=True, default='', max_length=20)),
                ('start_time_pre', models.TimeField()),
                ('stop_time_pre', models.TimeField()),
                ('room_name_pre', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preschedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=50)),
                ('Subject_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Teacher', models.CharField(blank=True, default='', max_length=100)),
                ('Room', models.CharField(blank=True, default='', max_length=50)),
                ('Room_Type', models.CharField(blank=True, default='', max_length=50)),
                ('Type', models.CharField(blank=True, default='', max_length=20)),
                ('Curriculum_Type', models.CharField(blank=True, default='', max_length=20)),
                ('Day', models.CharField(blank=True, default='', max_length=20)),
                ('Hour', models.IntegerField(default=0)),
                ('Time_Slot', models.CharField(blank=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Day', 'Hour', 'Course_Code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัสบดี', 'พฤหัสบดี'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], max_length=20)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time', 'stop_time', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='WeekActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name_activity', models.CharField(blank=True, default='', max_length=100)),
                ('day_activity', models.CharField(blank=True, default='', max_length=20)),
                ('hours_activity', models.IntegerField(default=0)),
                ('start_time_activity', models.TimeField(blank=True, null=True)),
                ('stop_time_activity', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='scheduler.roomtype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='scheduler.grouptype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='GroupAllow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_allows', to=settings.AUTH_USER_MODEL)),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_slots', to='scheduler.grouptype')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_type_allows', to='scheduler.timeslot')),
            ],
            options={
                'ordering': ['group_type__name', 'slot__day_of_week', 'slot__start_time'],
                'unique_together': {('group_type', 'slot', 'created_by')},
            },
        ),
    ]
