# Generated by Django 4.2.24 on 2025-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_generatedschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschedule',
            name='section_pre',
            field=models.CharField(max_length=10),
        ),
    ]
